name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # Si tu rama principal se llama 'master', cámbialo aquí

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get code from GitHub
        uses: actions/checkout@v4

      - name: Sync files to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/